---
- id: terraform-fmt
  name: terraform-fmt
  entry: terraform-fmt
  description: Rewrite Terraform configuration files to a canonical format and style
  language: python
  files: (\.tf|\.tfvars)$
  exclude: \.terraform\/.*$
  
- id: checkov-scan
  name: checkov
  description: runs checkov over a project
  entry: checkov-scan
  language: python
  language_version: 3.7
  files: (\.tf)$
  exclude: \.terraform\/.*$
  always_run: true
  pass_filenames: true
  verbose: true
