---
repos:
  - repo: https://github.com/ambv/black
    rev: c6755bb741b6481d6b3d3bb563c83fa060db96c9 # 26.3.1
    hooks:
      - id: black
        args:
          - --line-length=79
        language_version: python3
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: flake8
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/pre-commit
    rev: f35134b05028ec938ac605ae500fdf95462655d3 # v4.6.0
    hooks:
      - id: validate_manifest
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: bash -c 'python3 -m pytest tests/ -v'
        language: system
        pass_filenames: false
        always_run: true
